services:
  # Next.js application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pwa-next15-authjs
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/pwausers_db
      - NEXTAUTH_URL=http://localhost:3000
      - AUTH_TRUST_HOST=true
      - NEXTAUTH_SECRET=your-secret-key-change-this-in-production
      - PWA_AUTH_URL=https://intranet.pwa.co.th/login/webservice_login6.php
    depends_on:
      - db
    networks:
      - app-network

  # PostgreSQL database
  db:
    image: postgres:17.5-alpine3.20
    container_name: pwa-next15-authjs-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pwausers_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts:/scripts
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # pgAdmin web interface
  pgadmin:
    image: elestio/pgadmin:latest
    container_name: pwa-next15-authjs-pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=adminpassword
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
